### ISSUE TITLE
Suggestion on the guideline

### ISSUE THREAD

**Issue by FeiWang96** [danieljf24/w2vv#1]
Your work helps me a lot!

However, I met some problems when using it to train my own model and here are some suggestions. 
In "How to train Word2VisualVec on other datasets?" part:
Since ${feature_name} is changed and the dataset may have less than 5 sentences for each video, the model can't be trained use command "./do_all.sh ${train_set_name} ${val_set_name} ${test_set_name}".

I think it is better to change the guideline into:
train by 
./do_gene_vocab.sh $trainCollection
w2vv_trainer.py $trainCollection $valCollection  $testCollection --overwrite $overwrite  --img_feature=${feature_name} --n_caption=${caption_num}
evaluate by
./do_test_${testCollection}.sh

**Comment by danieljf24** [comment]
Thanks for your suggestion. We have modified our script for training on other datasets.
