### ISSUE TITLE
Is the code support Python3?

### ISSUE THREAD

**Issue by binfeng** [danieljf24/w2vv#12]
I think the pretrained vec500flickr30m is from Python2? In order to get a Python3 model, I will need to re-train?

**Comment by danieljf24** [comment]
You can first transfer the bin file of vec500flickr30m  into txt file by python2, and then convert txt into new bin file by python3 using [txt2bin.py](https://github.com/danieljf24/simpleknn/blob/master/txt2bin.py).  You can also refer to [here](https://github.com/danieljf24/dual_encoding#how-to-run-dual-encoding-on-another-datasets), the process is similar to generate bin file of video features.

**Comment by binfeng** [comment]
Thanks! Very helpful.
