### ISSUE TITLE
Question about training process

### ISSUE THREAD

**Issue by yuxinyan** [danieljf24/w2vv#2]
I have a question about the training process. In your code, you use 
`Class PairDataSet_MS()` to generate each batch data. However, the generator method
`getBatchData(self)` sample training with replacement. In a epoch, each training pair may not 
be sampled. Is it a mistake ?

**Comment by danieljf24** [comment]
Although some training pairs cannot be sampled in an epoch, all pairs will be sampled in multiple epochs. It's not a mistake and does not affect performance.
