### ISSUE TITLE
Video feature extraction - code still available?

### ISSUE THREAD

**Issue by ClaasM** [danieljf24/w2vv#4]
Hi,

First of all: thanks a lot for making this open source!

I'm trying to reproduce your video-to-sentence results in the TrecVid 2016 benchmark mentioned in [your paper](https://arxiv.org/pdf/1604.06838.pdf), alongside some of your other results with w2vv in video-caption-retrieval.

To my understanding you used mean-pooled GoogLeNet-shuffle/Resnet-152 concatenated with a 1024-dim MFCC as the audio feature. 

**Do you still have any of the code used to extract features from video?**

That would spare me a lot of trial and error in reproducing the results.

Thanks!

**Comment by danieljf24** [comment]
Sorry ClaasM, the code used in TRECVID 2016 is unavailable. But you are free to utilize the [features](https://github.com/li-xirong/avs) used in our entry for TRECVID 2018, which is stronger than that used for TRECVID 2016.
