### ISSUE TITLE
question of the concrete form of imagefeature.txt you use (before using txt2bin.py to convert image feature in the required binary format )

### ISSUE THREAD

**Issue by sherjy** [danieljf24/w2vv#6]

**Comment by sherjy** [comment]
Fristly, I'm grateful for your paper and codes, they help me a lot to understand the idea and something in specific implementation. 
Then I want to train and test the model on my datasets, but after I extract the features from images in some ways, I cannot use the txt2bin.py directly to convert my imagefeature.txt due to I'm not sure  the concrete form of imagefeature.txt you use (before using txt2bin.py to convert image feature in the required binary format ). **So could you give me the exact form  of imagefeature.txt?**
Thanks a lot !

**Comment by danieljf24** [comment]
[Here](https://github.com/danieljf24/w2vv/blob/master/simpleknn/toydata/FeatureData/f1/id.feature.txt)  is the example of imagefeature.txt
Each row is the combination of image id and feature, and separated by blank.

**Comment by sherjy** [comment]
very useful, thanks a lot!
