### ISSUE TITLE
question about training a new Word2vec model on my dataset (new tags/sentences of images)

### ISSUE THREAD

**Issue by sherjy** [danieljf24/w2vv#7]
Sorry to trouble again, I have a question about the experiments, when I want to use my images and sentences in a different domain，I need to pretrain a new word2vec model for myself and add to replace the three files in `/VisualSearch/word2vec/flickr/vec500flickr30m`.
Here is a question, I cannot use word2vec api or gensim to load your pre-trained word2vec model file——feature.bin. Also I don't know whether I use the right way to get the bin file as my dataset result. **So, could you tell me the right way to build the file(word2vec:feature.bin, id.txt, shape.txt) if I want to pre-train a new word2vec model to add to your codes and re-run.**
Hope for your help, thanks!

**Comment by danieljf24** [comment]
vec500flickr30m are word embedding vectors extracted by the trained word2vec model, so it is not supported for word2vec api or gensim.
You can use your trained word2vec model to extract word embedding vectors of the vocabulary, and save it in bin format [how](https://github.com/danieljf24/w2vv/issues/6).
