### ISSUE TITLE
How to retrieve similar sentences from image ?

### ISSUE THREAD

**Issue by mymuli** [danieljf24/w2vv#8]
After the model training is completed, how can I use any picture as input to retrieve the title closest to the content of the picture?

模型训练完成之后，我如何将任意一张图片作为输入，检索到最接近图片内容的标题呢？

**Comment by danieljf24** [comment]
You should first represent all the candidate captions in the visual space by a trained Word2VisualVec model. Given an image, you extract its visual feature by a pre-trained CNN (for example, ResNet), then compute its cosine similarities with all the candidate captions in the visual feature space. The captions are ranked in terms of the cosine similarity.

**Comment by mymuli** [comment]
I know how to do it. Thank you very much.
